### ISSUE TITLE
Production not processing TAIR file correctly

### ISSUE THREAD

**Issue by alexlancaster** [whitehead/plaac#1]
Download:

ftp://ftp.arabidopsis.org/home/tair/Proteins/TAIR10_protein_lists/TAIR10_pep_20101214

upload and try and run with default parameters, get ```Internal Server Error```

Maybe a server-side problem?

**Comment by oliverking** [comment]
Hi Andy and Alex,
I just tried pasting in sequences (one or two ) to PLAAC, but in neither
case do I see any images,  just placeholders. I tried Firefox and Safari.
Is this an issue of the server's frame buffer needing to be reset? I have
no idea how longs it's been in this state.
Best,
Oliver

**Comment by oliverking** [comment]
(Also, can the header on the main page be changed from *"PLAAC* searches
protein sequences to identify probable prion subsequences using a
hidden-Markov model (HMM) algorithm" to *"PLAAC* searches protein sequences
to identify subsequences with prion-like amino acid composition using a
hidden-Markov model (HMM) algorithm"?)

**Comment by oliverking** [comment]
I can see visualizations if I click on the pdf, but am troubled that I get
different plots if I paste in the sequence by itself or along with other
sequences.
Even get different results pasting it in by itself or by itself but twice.
With the following sequences. I get the same score (46.9) but have gotten
three wildly
different results for the track in the HMM parse and in the sliding-window
parse. In all cases I scer background set explicitly to 100%.
This is rather embarrassing --- can we take down the server until it is
sorted out?


>seq1
MGKKDKNKKGGQDSAAAPQPQQQQKQQQQRQQQPQQLQQPQQLQQPQQLQQPQQQQQQQPHQQQQQSSRQQPSTSSGGSR
ASGFQQGGQQQKSQDAEGWTAQKKQGKQQVQGWTKQGQQGGHQQGRQGQDGGYQQRPPGQQQGGHQQGRQGQEGGYQQRP
PGQQQGGHQQGRQGQEGGYQQRPSGQQQGGHQQGRQGQEGGYQQRPPGQQQGGHQQGRQGQEGGYQQRPSGQQQGGHQQG
RQGQEGGYQQRPPGQQQGGHQQGRQGQEGGYQQRPPGQQQGGHEQGRQGQEGGYQQRPSGQQQGGHQQGRQGQEGGYQQR
PSGQQQGGHQQGRQGQEGGYQQRPSGQQQGGHQQGRQGQEGGYQQRPPGQQPNQTQSQGQYQSRGPPQQQQAAPLPLPPQ
PAGSIKRGTIGKPGQVGINYLDLDLSKMPSVAYHYDVKIMPERPKKFYRQAFEQFRVDQLGGAVLAYDGKASCYSVDKLP
LNSQNPEVTVTDRNGRTLRYTIEIKETGDSTIDLKSLTTYMNDRIFDKPMRAMQCVEVVLASPCHNKAIRVGRSFFKMSD
PNNRHELDDGYEALVGLYQAFMLGDRPFLNVDISHKSFPISMPMIEYLERFSLKAKINNTTNLDYSRRFLEPFLRGINVV
YTPPQSFQSAPRVYRVNGLSRAPASSETFEHDGKKVTIASYFHSRNYPLKFPQLHCLNVGSSIKSILLPIELCSIEEGQA
LNRKDGATQVANMIKYAATSTNVRKRKIMNLLQYFQHNLDPTISRFGIRIANDFIVVSTRVLSPPQVEYHSKRFTMVKNG
SWRMDGMKFLEPKPKAHKCAVLYCDPRSGRKMNYTQLNDFGNLIISQGKAVNISLDSDVTYRPFTDDERSLDTIFADLKR
SQHDLAIVIIPQFRISYDTIKQKAELQHGILTQCIKQFTVERKCNNQTIGNILLKINSKLNGINHKIKDDPRLPMMKNTM
YIGADVTHPSPDQREIPSVVGVAASHDPYGASYNMQYRLQRGALEEIEDMFSITLEHLRVYKEYRNAYPDHIIYYRDGVS
DGQFPKIKNEELRCIKQACDKVGCKPKICCVIVVKRHHTRFFPSGDVTTSNKFNNVDPGTVVDRTIVHPNEMQFFMVSHQ
AIQGTAKPTRYNVIENTGNLDIDLLQQLTYNLCHMFPRCNRSVSYPAPAYLAHLVAARGRVYLTGTNRFLDLKKEYAKRT
IVPEFMKKNPMYFV

**Comment by andynu** [comment]
Hi Oliver,

Sorry for the delay. I've restarted the service. And Scott is adding a cron
to restart it nightly since it gives us no indication whatsoever that it is
not working correctly when it gets into that hung state.

--
Andy

**Comment by alexlancaster** [comment]
Something does seem up in that pressing return in the text box, doesn't move the cursor to the following line.

**Comment by alexlancaster** [comment]
I cut and pasted the identical sequence and it seemed to work OK if I made sure to give them different names, e.g. "seq1" and "seq2":  http://plaac.wi.mit.edu/visualize/b93ebd50-ba0b-0132-1c80-0022640b516e

**Comment by alexlancaster** [comment]
Tested using

```
>testQ70a
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
```

http://plaac.wi.mit.edu/visualize/87d7db10-c04c-0132-1d1d-0022640b516e

followed by:

```
>testQ70a
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
>testQ70b
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
```

and now I get the same results for the single and two sequence cases.  @oliverking let me know if you get the same

**Comment by alexlancaster** [comment]
Also the originally reported problem at the top of the issue (loading the TAIR dataset) seems fixed now, too.

**Comment by oliverking** [comment]
yes, thanks.
